(function() {var implementors = {};
implementors["libsignal_protocol"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.TryFrom.html\" title=\"trait core::convert::TryFrom\">TryFrom</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.i32.html\">i32</a>&gt; for <a class=\"enum\" href=\"libsignal_protocol/crypto/enum.SignalCipherType.html\" title=\"enum libsignal_protocol::crypto::SignalCipherType\">SignalCipherType</a>",synthetic:false,types:["libsignal_protocol::crypto::SignalCipherType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.TryFrom.html\" title=\"trait core::convert::TryFrom\">TryFrom</a>&lt;<a class=\"struct\" href=\"libsignal_protocol/messages/struct.CiphertextMessage.html\" title=\"struct libsignal_protocol::messages::CiphertextMessage\">CiphertextMessage</a>&gt; for <a class=\"struct\" href=\"libsignal_protocol/messages/struct.PreKeySignalMessage.html\" title=\"struct libsignal_protocol::messages::PreKeySignalMessage\">PreKeySignalMessage</a>",synthetic:false,types:["libsignal_protocol::messages::pre_key_signal_message::PreKeySignalMessage"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.TryFrom.html\" title=\"trait core::convert::TryFrom\">TryFrom</a>&lt;<a class=\"struct\" href=\"libsignal_protocol/messages/struct.CiphertextMessage.html\" title=\"struct libsignal_protocol::messages::CiphertextMessage\">CiphertextMessage</a>&gt; for <a class=\"struct\" href=\"libsignal_protocol/messages/struct.SignalMessage.html\" title=\"struct libsignal_protocol::messages::SignalMessage\">SignalMessage</a>",synthetic:false,types:["libsignal_protocol::messages::signal_message::SignalMessage"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
